Renamed and Updated
sasakiassociates/speckle pull request #7
Opened 2023-08-14 15:18 UTC by haitheredavid

Bumped object loader and added new naming convention to match FE2 with speckle.

2023-08-14 19:36 UTC, ericyoungberg requested changes
Looks great! I only flagged one thing which is a missed variable rename; looks like you caught the rest.

2023-08-14 19:36 UTC, ericyoungberg commented on src/ObjectReference.ts
> +    public get stream(): Project {
`project` instead of `stream`

2023-08-14 23:09 UTC, haitheredavid commented
@ericyoungberg  updated and caught a few more naming things

2023-08-15 14:35 UTC, ericyoungberg approved these changes

2023-08-16 21:58 UTC, merged